<a href="https://colab.research.google.com/github/suprabhat25/FrozenLake/blob/main/FrozenLake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install gym

In [1]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0") # creating the environment

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1  # alpha
discount_rate = 0.99 # gamma

#below all are related to exploration - exploitation trade off
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [10]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

           # Exploration - exploitation trade off
           exploration_rate_threshold = random.uniform(0,1) 
           if exploration_rate_threshold > exploration_rate: #exploitation
             action = np.argmax(q_table[state,:])
           else:
             action = env.action_space.sample() #exploration
           
           new_state, reward, done, info = env.step(action)


           #Update Q - table for Q(s,a)

           q_table[state, action] = (q_table[state, action] * (1-learning_rate) + 
                   learning_rate * (reward + discount_rate * np.max(q_table[new_state, :])) )
    
           state = new_state
           rewards_current_episode += reward

           if done == True : 
                break

       # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate *episode)
    rewards_all_episodes.append(rewards_current_episode)

#Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("Average reward per thousand episodes\n")
for r in rewards_per_thousand_episodes:
  print(count," : ", str(sum(r/1000)))
  count+=1000
print()
#Print updated Q-table
print("            Q-table           \n")
print(q_table)


Average reward per thousand episodes

1000  :  0.46200000000000035
2000  :  0.6830000000000005
3000  :  0.6910000000000005
4000  :  0.6710000000000005
5000  :  0.6730000000000005
6000  :  0.6860000000000005
7000  :  0.6810000000000005
8000  :  0.6920000000000005
9000  :  0.6660000000000005
10000  :  0.6720000000000005

            Q-table           

[[0.53657679 0.50754258 0.5049298  0.50406732]
 [0.22916582 0.14180697 0.24973354 0.46975211]
 [0.43647656 0.23057953 0.158142   0.23563941]
 [0.18372877 0.01493798 0.         0.02878895]
 [0.55541822 0.39813996 0.3300869  0.33206004]
 [0.         0.         0.         0.        ]
 [0.40441925 0.18159926 0.14228443 0.07791366]
 [0.         0.         0.         0.        ]
 [0.44663894 0.40487064 0.30331341 0.59533074]
 [0.47180538 0.66126792 0.21683316 0.42964982]
 [0.62272686 0.39105854 0.34558961 0.34471676]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.38716309 0.57983771 0.75151729 0

In [11]:
for episode in range(3):
  state = env.reset()
  done = False
  print("Episode ",episode+1,"\n")
  time.sleep(1)

  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)

    action = np.argmax(q_table[state,:])
    new_state, reward, done, info = env.step(action)

    if done:
      clear_output(wait=True)
      env.render()
      if reward == 1:
        print("Goal")
        time.sleep(3)
      else:
        print("Failed")
        time.sleep(3)
      clear_output(wait=True)
      break

    state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
Goal
