<a href="https://colab.research.google.com/github/suprabhat25/FrozenLake/blob/main/FrozenLake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install gym

In [6]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output

In [7]:
env = gym.make("FrozenLake-v0") # creating the environment

In [10]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1  # alpha
discount_rate = 0.9  # gamma

#below all are related to exploration - exploitation trade off
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [28]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

           # Exploration - exploitation trade off
           exploration_rate_threshold = random.uniform(0,1) 
           if exploration_rate_threshold > exploration_rate: #exploitation
             action = np.argmax(q_table[state,:])
           else:
             action = env.action_space.sample() #exploration
           
           new_state, reward, done, info = env.step(action)


           #Update Q - table for Q(s,a)

           q_table[state, action] = (q_table[state, action] * (1-learning_rate) + 
                   learning_rate * (reward + discount_rate * np.max(q_table[new_state, :])) )
    
           state = new_state
           rewards_current_episode += reward

           if done == True : 
                break

       # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate *episode)
    rewards_all_episodes.append(rewards_current_episode)

#Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("Average reward per thousand episodes\n")
for r in rewards_per_thousand_episodes:
  print(count," : ", str(sum(r/1000)))
  count+=1000
print()
#Print updated Q-table
print("            Q-table           \n")
print(q_table)


Average reward per thousand episodes

1000  :  0.06200000000000005
2000  :  0.1480000000000001
3000  :  0.2720000000000002
4000  :  0.43900000000000033
5000  :  0.4180000000000003
6000  :  0.5240000000000004
7000  :  0.5660000000000004
8000  :  0.5700000000000004
9000  :  0.5120000000000003
10000  :  0.5900000000000004

            Q-table           

[[0.08317674 0.04779861 0.04762641 0.04783264]
 [0.03659547 0.03590102 0.0331244  0.04961874]
 [0.06331169 0.05251414 0.04612354 0.04507445]
 [0.01887794 0.0296295  0.02998689 0.03691475]
 [0.11604052 0.05991918 0.05986533 0.05494593]
 [0.         0.         0.         0.        ]
 [0.10214615 0.02600912 0.06286759 0.02792299]
 [0.         0.         0.         0.        ]
 [0.07154654 0.07453054 0.07274464 0.15255958]
 [0.16262473 0.28263978 0.14002082 0.14014292]
 [0.43466377 0.11827612 0.19667574 0.10874735]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.18785824 0.18196747 0.4314159  